name: pchem
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pandas=1.3.2
  - openai=0.10.4
  - plotly=5.3.1
  - scipy=1.7.1
  - sympy=1.8
  - json_tricks=3.15.5
  - coolprop=6.4.1
  - pip
  - pip:
    - openai==0.10.4
    - streamlit==0.88.0
    - streamlit-ace==0.1.0
